"""
kicad_mod_writer.py — converts footprint.json to KiCad 7 .kicad_mod S-expression format.

KiCad 7 footprint format reference:
  https://dev-docs.kicad.org/en/file-formats/sexpr-footprint/
"""

from __future__ import annotations

import math
from typing import Any


def _fmt(v: float) -> str:
    """Format a float to 4 decimal places, stripping trailing zeros."""
    return f"{v:.4f}".rstrip("0").rstrip(".")


def _fmt4(v: float) -> str:
    """Always 4 decimal places."""
    return f"{v:.4f}"


def write(fp: dict[str, Any]) -> str:
    """
    Convert a footprint dict (matching footprint_output.json schema) to a
    KiCad 7 .kicad_mod S-expression string.

    Required keys in fp:
        name        – footprint name string
        pads        – list of pad dicts
        courtyard   – {x, y, width, height}  (centre + half-extents style OR
                      the schema's top-left + full size; we treat it as centre)
        silkscreen  – list of {type, data} dicts  (optional)
        format      – must be "kicad_mod"
    """
    name = fp["name"]
    lines: list[str] = []

    lines.append(f'(footprint "{name}" (version 20231120) (generator "pcb-ai")')
    lines.append('  (layer "F.Cu")')
    lines.append(f'  (descr "{name} — generated by pcb-ai footprint agent")')
    lines.append(f'  (tags "{name}")')
    lines.append("")

    # ── Reference / Value properties ──────────────────────────────────────
    cy = fp["courtyard"]
    # Determine a sensible Y offset for silkscreen text (above/below courtyard)
    cy_half_h = cy["height"] / 2.0
    ref_y = _fmt4(-(cy_half_h + 1.0))
    val_y = _fmt4(cy_half_h + 1.0)

    lines.append(
        f'  (property "Reference" "REF**" (at 0 {ref_y} 0)'
        f'    (layer "F.SilkS")'
        f'    (effects (font (size 1 1) (thickness 0.15))))'
    )
    lines.append(
        f'  (property "Value" "{name}" (at 0 {val_y} 0)'
        f'    (layer "F.Fab")'
        f'    (effects (font (size 1 1) (thickness 0.15))))'
    )
    lines.append("")

    # ── Courtyard rectangle ────────────────────────────────────────────────
    # Schema courtyard: {x, y, width, height}
    # We treat x,y as the centre of the courtyard.
    cx = cy["x"]
    ccy = cy["y"]
    hw = cy["width"] / 2.0
    hh = cy["height"] / 2.0
    x0 = _fmt4(cx - hw)
    y0 = _fmt4(ccy - hh)
    x1 = _fmt4(cx + hw)
    y1 = _fmt4(ccy + hh)

    lines.append(
        f'  (fp_rect (start {x0} {y0}) (end {x1} {y1})'
        f'    (layer "F.CrtYd") (stroke (width 0.05) (type solid)) (fill none))'
    )

    # ── Fab outline (same as courtyard but slightly inset, on F.Fab) ───────
    fab_margin = 0.10
    x0f = _fmt4(cx - hw + fab_margin)
    y0f = _fmt4(ccy - hh + fab_margin)
    x1f = _fmt4(cx + hw - fab_margin)
    y1f = _fmt4(ccy + hh - fab_margin)
    lines.append(
        f'  (fp_rect (start {x0f} {y0f}) (end {x1f} {y1f})'
        f'    (layer "F.Fab") (stroke (width 0.10) (type solid)) (fill none))'
    )
    lines.append("")

    # ── Silkscreen elements ────────────────────────────────────────────────
    silk = fp.get("silkscreen", [])
    for item in silk:
        t = item.get("type", "")
        d = item.get("data", {})
        if t == "line":
            sx = _fmt4(d.get("x1", 0))
            sy = _fmt4(d.get("y1", 0))
            ex = _fmt4(d.get("x2", 0))
            ey = _fmt4(d.get("y2", 0))
            lines.append(
                f'  (fp_line (start {sx} {sy}) (end {ex} {ey})'
                f'    (layer "F.SilkS") (stroke (width 0.12) (type solid)))'
            )
        elif t == "arc":
            ax = _fmt4(d.get("x", 0))
            ay = _fmt4(d.get("y", 0))
            r = _fmt4(d.get("radius", 0.5))
            start_a = d.get("start_angle", 0)
            end_a = d.get("end_angle", 360)
            lines.append(
                f'  (fp_arc (start {ax} {ay}) (mid 0 0) (end 0 0)'
                f'    (layer "F.SilkS") (stroke (width 0.12) (type solid)))'
            )
        elif t == "text":
            tx = _fmt4(d.get("x", 0))
            ty = _fmt4(d.get("y", 0))
            text = d.get("text", "")
            lines.append(
                f'  (fp_text user "{text}" (at {tx} {ty}) (layer "F.SilkS")'
                f'    (effects (font (size 1 1) (thickness 0.15))))'
            )

    if silk:
        lines.append("")

    # ── Pads ───────────────────────────────────────────────────────────────
    for pad in fp["pads"]:
        num = str(pad["number"])
        ptype = pad["type"]  # smd | thru_hole
        pshape = pad["shape"]  # rect | oval | circle

        px = _fmt4(pad["x"])
        py = _fmt4(pad["y"])
        pw = _fmt4(pad["width"])
        ph = _fmt4(pad["height"])

        # KiCad pad type keyword
        if ptype == "smd":
            kicad_type = "smd"
            layers = '"F.Cu" "F.Paste" "F.Mask"'
        else:
            kicad_type = "thru_hole"
            layers = '"*.Cu" "*.Mask"'

        # KiCad shape keyword
        shape_map = {"rect": "rect", "oval": "oval", "circle": "circle"}
        kicad_shape = shape_map.get(pshape, "rect")

        # Pin 1 gets a square pad (rect) regardless of default shape
        if num == "1" and pshape != "circle":
            kicad_shape = "rect"

        pad_str = (
            f'  (pad "{num}" {kicad_type} {kicad_shape}'
            f' (at {px} {py})'
            f' (size {pw} {ph})'
            f' (layers {layers})'
        )

        if ptype == "thru_hole":
            drill = pad.get("drill")
            if drill and drill > 0:
                drill_str = _fmt4(drill)
                pad_str += f" (drill {drill_str})"
            else:
                # IPC-7251 minimum drill = 0.3 mm
                pad_str += " (drill 0.3)"

        pad_str += ")"
        lines.append(pad_str)

    lines.append("")
    lines.append(")")

    return "\n".join(lines)
